import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

const repoRoot = process.cwd()

function toCssVarName(tokenName) {
  return `--lg-${tokenName.split('.').join('-')}`
}

async function main() {
  const srcPath = path.join(repoRoot, 'src', 'tokens.json')
  const publicDir = path.join(repoRoot, 'public')

  const raw = await fs.readFile(srcPath, 'utf8')
  const tokens = JSON.parse(raw)

  if (!Array.isArray(tokens)) {
    throw new Error('Expected src/tokens.json to be an array')
  }

  await fs.mkdir(publicDir, { recursive: true })

  const jsonOutPath = path.join(publicDir, 'tokens.json')
  await fs.writeFile(jsonOutPath, `${JSON.stringify(tokens, null, 2)}\n`, 'utf8')

  const header = [
    '/*',
    '  Liquid Glass UI — token export',
    '  Generated by scripts/generate-tokens.mjs from src/tokens.json',
    '*/',
    '',
  ].join('\n')

  const lines = tokens.map((token) => {
    if (
      !token ||
      typeof token !== 'object' ||
      typeof token.name !== 'string' ||
      typeof token.value !== 'string'
    ) {
      throw new Error('Invalid token shape in src/tokens.json')
    }
    return `  ${toCssVarName(token.name)}: ${token.value};`
  })

  const css = `${header}:root {\n${lines.join('\n')}\n}\n`
  const cssOutPath = path.join(publicDir, 'tokens.css')
  await fs.writeFile(cssOutPath, css, 'utf8')
}

await main()
